services:
    users_db:
        image: mysql
        container_name: users_db
        ports:
            - 3392:3306
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 10s
            retries: 10
            interval: 10s
            start_period: 10s
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users_db
        networks:
            - churchnetwork

    church_details_db:
        image: mysql
        container_name: church_details_db
        ports:
            - 3391:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 10s
            retries: 10
            interval: 10s
            start_period: 10s
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: church_details_db
        networks:
            - churchnetwork

    users:
        image: "tony710/user:v1"
        container_name: user-ms
        ports:
            - "9091:9091"
        healthcheck:
            test: "curl --fail --silent localhost:9091/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        environment:
            SPRING_APPLICATION_NAME: "users"
            SPRING_DATASOURCE_URL: "jdbc:mysql://users_db:3306/users_db"
        depends_on:
            users_db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 900m
        networks:
            - churchnetwork

    church_details:
        image: "tony710/church_detail:v1"
        container_name: church-detail-ms
        ports:
            - "9090:9090"
        healthcheck:
            test: "curl --fail --silent localhost:9090/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        environment:
            SPRING_APPLICATION_NAME: "church-details"
            SPRING_DATASOURCE_URL: "jdbc:mysql://church_details_db:3306/church_details_db"
        depends_on:
            church_details_db:
                condition: service_healthy
            eurekaserver:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 900m
        networks:
            - churchnetwork

    gatewayserver:
        image: "tony710/gatewayserver:v1"
        container_name: gatewayserver-ms
        ports:
            - "10010:10010"
        environment:
            SPRING_APPLICATION_NAME: "gatewayserver"
        depends_on:
            church_details:
                condition: service_healthy
            users:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 900m
        networks:
            - churchnetwork

    eurekaserver:
        image: "tony710/eurekaserver:v1"
        container_name: eurekaserver
        ports:
            - "8761:8761"
        healthcheck:
            test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        environment:
            SPRING_APPLICATION_NAME: "eurekaserver"
        deploy:
            resources:
                limits:
                    memory: 900m
        networks:
            - churchnetwork

networks:
    churchnetwork:
        driver: "bridge"
