spring:
  datasource:
      url: jdbc:mysql://localhost:3392/users_db
      username: root
      password: root
  jpa:
      show-sql: true
      defer-datasource-initialization: true
  sql:
    init:
        mode: always
  docker:
    compose:
        enabled: false

  application:
      name: "users"

server:
    port: 9091

management:
    info:
        env:
            enabled: true
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true
        health:
          probes:
            enabled: true

endpoints:
    shutdown:
        enabled: true

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://eurekaserver:8761/eureka/
info:
    app:
        name: "users-ms"
        description: "setting up users with roles"
