spring:
  datasource:
      url: jdbc:mysql://localhost:3391/church_details_db
      username: root
      password: root
  jpa:
      show-sql: true
      defer-datasource-initialization: true
  sql:
    init:
        mode: always
  docker:
    compose:
        enabled: false
  application:
      name: "church_details"
server:
    port: 9090

management:
  info:
      env:
          enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoints:
      web:
          exposure:
              include: "*"
  endpoint:
    shutdown:
        enabled: true
    health:
      probes:
        enabled: true

endpoints:
    shutdown:
        enabled: true

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://eurekaserver:8761/eureka/
info:
  app:
      name: "church_details"
      description: "church"
